### ISSUE TITLE
Distiller JEI support does not show secondary outputs.

### ISSUE THREAD

**Issue by TeetoKaziim** [tgstyle/MCT-Immersive-Technology#118]
Forge: 14.23.5.2847
JEI: 4.15.0.293
Immersive Technology: 1.7.60

Pressing "R" (to show recipe) on Salt Dust (immersivetech:material:0) (or an item added as a secondary output to distilling other things via crafttweaker), will bring up the JEI tab for the distiller.

But in the JEI UI for the distiller, the salt (or other secondary) output is not displayed.
![image](https://user-images.githubusercontent.com/25490944/82640897-0609d800-9bd1-11ea-9ed0-43f2a0714daf.png)

The secondary output is DEFINITELY happening, though, that part works as advertised.

**Comment by Kurtchekov** [comment]
Wow, I hadn't realized that! Will start working on it ASAP
