### ISSUE TITLE
Redstone Timer not shutting off when signal is applied

### ISSUE THREAD

**Issue by Gunner76th** [tgstyle/MCT-Immersive-Technology#120]
So on Engineer's Life version 2.01https://www.curseforge.com/minecraft/modpacks/engineers-life
We have an issue in that the Redstone Timer refuses to stop when a signal is applied to the input point on the side. 

![image](https://user-images.githubusercontent.com/5566872/83917564-21cebb80-a745-11ea-80ac-2b0a90ba6a35.png)

As you can see I have a lever with an input connector attached to the the block feeding signal to both the Redstone Lamp and the Timer. The Lamp is lit, but the timer continues to cycle. I can also put the lever directly on the Timer with no chance in operation.  All connectors are on the same color, and all connectors are configured correctly (input vs output)

**Comment by Gunner76th** [comment]
![image](https://user-images.githubusercontent.com/5566872/83917802-7d994480-a745-11ea-85c8-9a687121f190.png)

For reference, according to the manual this should be turning off the timer, but as I said, it does not.

**Comment by Kurtchekov** [comment]
I've just checked it here and it works as intended. Have you changed that Redstone Wire Connector attached to the timer to be output?

**Comment by Kurtchekov** [comment]
Since you have used the lever directly on the timer and it didn't work, would it be possible to get the save file and send it over?

**Comment by Kurtchekov** [comment]
Okay, I have figured the issue. It only happens if you have more than one timer chunkloaded in the world, will be fixing it in a moment. Disregard my previous messages.

**Comment by Kurtchekov** [comment]
[IT.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/4739355/IT.zip)
I don't know how long it's gonna take to release an update on Curseforge so here's a version you can play with in the meantime, should have the timer working as intended, regardless of how many timers you have in the world.
