### ISSUE TITLE
Question: Why are you extending IE's pipes?

### ISSUE THREAD

**Issue by BluSunrize** [tgstyle/MCT-Immersive-Technology#123]
Quite frankly, it seems to cause quite a few issues. If you have a suggestion for a better algorithm, why not just open a pullrequest and improve IE's core rather than extend & replace it, causing various compatability issues?

The least you could do is not put *my* name in the copyright, because I sure didn't write that.

**Comment by Kurtchekov** [comment]
@BluSunrize It's simple, I didn't want to go through this https://github.com/BluSunrize/ImmersiveEngineering/pull/3440 again. Also, we weren't sure you'd want to make any big changes to 1.12 and rather focus on the latest versions of the game instead.

**Comment by tgstyle** [comment]
The pipe code in the link below is 99.9% IE code. We can remove the copyright, but the only thing we changed was the formatting and fixed an NPE issue with IE pipes on chunk loads. The alternative algorithm is 100% @Kurtchekov's code and is only enabled if someone chooses to do so.

https://github.com/tgstyle/MCT-Immersive-Technology/blob/Latest/src/main/java/mctmods/immersivetechnology/common/blocks/metal/tileentities/TileEntityFluidPipe.java
