### ISSUE TITLE
Boiler Output Capped at 1,000 mb/t

### ISSUE THREAD

**Issue by Doublehelix13** [tgstyle/MCT-Immersive-Technology#129]
The boiler can be made to produce more than 1,000 mb/t of steam with Crafttweaker, but can only output 1,000 mb/t.  I am using super-laminar fluiducts, which have a limitless transfer rate.  The boiler's output tank fills up as it is producing more steam than it can output.

**Comment by Kurtchekov** [comment]
Have you tried using servos to pull fluids faster?

**Comment by tgstyle** [comment]
@Kurtchekov I just tested and the servo actually is worse, drops it down to 600mb/t. It's hard coded on the output of the TE for 1000mb/t. I am going to look in to making it a configurable option on the output. Or even dynamic by what is detected.

**Comment by tgstyle** [comment]
https://github.com/tgstyle/MCT-Immersive-Technology/commit/effdc4b8e4f1332e466ac5f1319fc833e803281b
