### ISSUE TITLE
Machines do not automatically output fluids

### ISSUE THREAD

**Issue by sinsinewave** [tgstyle/MCT-Immersive-Technology#134]
As the title states, Immersive Technology machines seem to not output fluids automatically like Immersive Engineering ones do, instead requiring a fluid pump directly on the output

**Comment by tgstyle** [comment]
Going to need more details then that. What version of the mod? I have not been able to reproduce this on the latest version of the mod.

**Comment by sinsinewave** [comment]
Mod version is 1.7.66, In this case the setup was a pipe running directly from a distiller output to a regular IE fluid tank

**Comment by tgstyle** [comment]
Any specific dimension? Overworld, Nether?

**Comment by sinsinewave** [comment]
Overworld, in a multiplayer game in case that matters

**Comment by tgstyle** [comment]
Can you try this version and see if it makes any difference?
https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology/files/3008414

**Comment by sinsinewave** [comment]
Having a hard time convincing our server admin to update so it may take a while, but I did notice a commit message about fixing the issue at some point, so I'm quite sure that version would work

**Comment by Andrey-007** [comment]
left boiler running right mirror boiler no steam output
version mc 1.12.2 forge 14.23.5.2854,  IE 0.12-98, MCT IT-1.7.70 photo yandex disk https://yadi.sk/d/RhTZepSXpEBQWA?w=1

**Comment by tgstyle** [comment]
@Andrey-007 I don't see any pictures in the link?

**Comment by Andrey-007** [comment]
> @ Andrey-007 Я не вижу картинки в ссылке?

sorry, but where should I put it?

**Comment by tgstyle** [comment]
@Andrey-007 I think you can post them right in to GitHub, drag and drop.

**Comment by Andrey-007** [comment]
![1](https://user-images.githubusercontent.com/17749204/88468326-75aa8500-ceea-11ea-9250-c2d7c3fbd41f.png)
![2](https://user-images.githubusercontent.com/17749204/88468327-78a57580-ceea-11ea-8bbb-755fce864553.png)
![3](https://user-images.githubusercontent.com/17749204/88468328-79d6a280-ceea-11ea-84d1-dec5301d4dd4.png)
![4](https://user-images.githubusercontent.com/17749204/88468330-7a6f3900-ceea-11ea-9b14-8c04cc1e09d3.png)
![5](https://user-images.githubusercontent.com/17749204/88468331-7ba06600-ceea-11ea-9f83-ffd127622a1f.png)

**Comment by Andrey-007** [comment]
Sorry in advance for my shitty english i use google translator

**Comment by tgstyle** [comment]
See if this version fixes it.
https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology/files/3014942

**Comment by Andrey-007** [comment]
Thank you, it works

**Comment by tgstyle** [comment]
I am going to consider this fully resolved. If there are any new issues please open a new one.
