### ISSUE TITLE
Crash on loading existing world with Immersive Engineering

### ISSUE THREAD

**Issue by SableDrake** [tgstyle/MCT-Immersive-Technology#135]
The world used to have Immersive Tech, has been removed, started, multiblocks broken, saved. After that I added Immersive Technology, world crashes on load.
[crash-2020-07-17_20.54.42-server.txt](https://github.com/tgstyle/MCT-Immersive-Technology/files/4939718/crash-2020-07-17_20.54.42-server.txt)

When trying to load a backup that had not been "cleaned" of Immersive Tech the following crash occurs: 
[crash-2020-07-17_21.11.27-server.txt](https://github.com/tgstyle/MCT-Immersive-Technology/files/4939774/crash-2020-07-17_21.11.27-server.txt)

**Comment by tgstyle** [comment]
@Kurtchekov that first crash is interesting with the CME.

The second crash is also interesting, when it tries to reform the blocks on conversion, error because of no hammer?

**Comment by Kurtchekov** [comment]
Yeah, player is null and therefore we can't get to see the hammer. @SableDrake when you tried removing the original IT first and replaced with this one, did you have the experimental pipes added by this mod enabled in your config file?

**Comment by tgstyle** [comment]
@Kurtchekov He did but I had him try disabling them. Same result either way.

**Comment by Kurtchekov** [comment]
It could be another mod causing that exception. Remember, that's a bug introduced by Forge, any mod can trigger it under the right circumstances.
