### ISSUE TITLE
Advanced Coke Oven not Working

### ISSUE THREAD

**Issue by nalilord** [tgstyle/MCT-Immersive-Technology#138]
In version 1.7.66 and 1.7.67 the Advanced Coke Oven is not working anymore. We reverted back to the version we used before (1.7.63) and it is working again.

**Comment by Kurtchekov** [comment]
Can you tell us more? How exactly is it not working? Does it accept items? Does the multiblock structure form at all? Is it just not processing recipes?

**Comment by nalilord** [comment]
Of course; With not working I mean it is not processing the input, I tried coal and coal blocks. The multiblock forms fine and accepts items, I removed it and placed it somewhere else and restarted the server multiple times with the oven formed and removed.

**Comment by Kurtchekov** [comment]
We have identified the problem and will be fixing it ASAP. Thanks for the report!

**Comment by tgstyle** [comment]
https://github.com/tgstyle/MCT-Immersive-Technology/pull/139

**Comment by tgstyle** [comment]
@nalilord can you try this version before I release it?
https://www.dropbox.com/s/a1r7ou9us1dnt1a/MCTImmersiveTechnology-1.12.2-1.7.68.jar?dl=1

**Comment by nalilord** [comment]
> @nalilord can you try this version before I release it?
> https://www.dropbox.com/s/a1r7ou9us1dnt1a/MCTImmersiveTechnology-1.12.2-1.7.68.jar?dl=1

Yes, it's working in this version.

**Comment by tgstyle** [comment]
Thanks!
