### ISSUE TITLE
Crash, extract empty creative metal barrel

### ISSUE THREAD

**Issue by Andrey-007** [tgstyle/MCT-Immersive-Technology#146]
Hello, I put a creative metal barrel on the extraction pipe enderioconduits crashed the client and now won't start.
This is the case with mods - appliedenergistics2, thermaldynamics, enderioconduits.
![1](https://user-images.githubusercontent.com/17749204/88883721-af0e2800-d23d-11ea-9f5d-bca877d21a06.png)
![2](https://user-images.githubusercontent.com/17749204/88883816-e250b700-d23d-11ea-9fa8-e741d7079727.png)
right click and crash the client
crash
1 [crash-2020-07-30_06.12.27-server.txt](https://github.com/tgstyle/MCT-Immersive-Technology/files/4998967/crash-2020-07-30_06.12.27-server.txt)
2 [crash-2020-07-30_05.26.35-server.txt](https://github.com/tgstyle/MCT-Immersive-Technology/files/4998971/crash-2020-07-30_05.26.35-server.txt)
3 [crash-2020-07-30_06.41.45-server.txt](https://github.com/tgstyle/MCT-Immersive-Technology/files/4998973/crash-2020-07-30_06.41.45-server.txt)

**Comment by tgstyle** [comment]
https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology/files/3020089
