### ISSUE TITLE
errors when placing trash cans

### ISSUE THREAD

**Issue by Lodugh** [tgstyle/MCT-Immersive-Technology#15]
I am getting these errors when placing trash cans:
[crash-2020-01-29_19.57.33-server.txt](https://github.com/tgstyle/Immersive-Technology/files/4130157/crash-2020-01-29_19.57.33-server.txt)
It spams crash reports and probably causes some performance issues. Would be great if you could fix it!

**Comment by tgstyle** [comment]
Just out of curiosity, do you have Redstone Flux installed?

**Comment by Kurtchekov** [comment]
EnumFacing can sometimes be null, that's probably what's causing the NPE. Should I fix it here?

**Comment by tgstyle** [comment]
Sure, if you have a fix in mind. I have not been able to look in to it as of yet.

**Comment by tgstyle** [comment]
Barring any issues that come up in testing today, there should be a release with the fix.
