### ISSUE TITLE
Craftweaker Cooling Tower

### ISSUE THREAD

**Issue by Liam-McCormack-Github** [tgstyle/MCT-Immersive-Technology#159]
mods.immersivetechnology.CoolingTower.addRecipe(<liquid:stabilizer> * 750, <liquid:stabilizer> * 750, <liquid:exhauststeam> * 300, <liquid:water> * 900, 3);

[SERVER_STARTED][SERVER][ERROR] script.zs:710 > No such member: CoolingTower

**Comment by Kurtchekov** [comment]
@thewawpro thanks for the report! I have fixed the problem on our end. To make sure it also works on your end (once the updated version comes out), your script should be as follows 
```
import mods.immersivetechnology.CoolingTower;

mods.immersivetechnology.CoolingTower.addRecipe(<liquid:stabilizer> * 750, <liquid:stabilizer> * 750, <liquid:exhauststeam> * 300, <liquid:water> * 900, 3);
```
