### ISSUE TITLE
1.12.2 Unable to get Y-rotated facing of down

### ISSUE THREAD

**Issue by YOYOK9** [tgstyle/MCT-Immersive-Technology#172]
Initially this crash was just affecting Immersive Petroleum However now it is effecting your mod as well. The crash is from a player on my server. For the longest time there was no issue with the coke oven till now. My server does use sponge forge (yes I know it sucks but its the best we have atm...) Have tested in Single player and no crash occurred. However the one on the server had been built a few days ago so no changes on why it is crashing now. 

MC: 1.12.2
Forge: 14.23.5.2854
IE: ImmersiveEngineering-0.12-98
IT: MCTImmersiveTechnology-1.12.2-1.7.72
Sponge: 1.12.2-2838-7.2.2

Crash: https://pastebin.com/niGbNQPy

**Comment by tgstyle** [comment]
Have you tried testing on a server without sponge forge?

**Comment by YOYOK9** [comment]
We are setting up a little server to test that now, If it is sponge is it something we should take to them? or could it be fixed on your end?

**Comment by tgstyle** [comment]
If it's sponge it's their issue. There would be nothing to change on our side since it would be fine with just forge.

**Comment by YOYOK9** [comment]
Figured, Ill let you know as soon as we have it up and running if it is sponge or not. Thank you for the help so far though, Love the quick responses

**Comment by YOYOK9** [comment]
Removed sponge and the issue seems to have gone as well. Thank you for the help.

**Comment by YOYOK9** [comment]
Seems I had spoke too soon. We removed sponge and all its plugins and replaced what we needed with FTB Utilities, After a few days the Y-Rotation crash returned starting with the Advanced coke oven. 

Forge and mods are still the same as above minus spongeforge. 

Crash: https://pastebin.com/Xe0RvPMz

**Comment by Kurtchekov** [comment]
Any chance you could send us the world save folder? I'm suspecting that machine might have corrupted NBT data stored by the server and is crashing the client.

**Comment by YOYOK9** [comment]
Umm it is possible, What would be the best way to do so? It is a rather large folder, 6.10GB.

**Comment by Kurtchekov** [comment]
Do you know what dimension that machine is in? All I need is the nbt data files (.mca extension), that should simplify things.

**Comment by YOYOK9** [comment]
I do yes, They are in the over world. Just trying to locate set file.

**Comment by Kurtchekov** [comment]
Should be the region folder, if that's not too big xD

**Comment by YOYOK9** [comment]
5.68Gb.. 
[region.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/5152700/region.zip)

**Comment by Kurtchekov** [comment]
Wait, the region folder is 5.68gb? How is that even possible! By the way, that zip file has a region folder but nothing else inside.

**Comment by Kurtchekov** [comment]
If my calculations are correct, the machine might be in either of these files: r.-4.0.mca, r.-3.0.mca, r.-4.1.mca, r.-3.1.mca. How big are those?

**Comment by YOYOK9** [comment]
Sorry it wouldnt let me upload the full world.zip from our host some reason, as for the files:
r.-3.0.mca: 7.08 MB
r.-3.1.mca: 9.24 MB
r.-4.0.mca: 7.58 MB
r.-4.1.mca: 8.57 MB

Which github wont let me upload those in a zip now either. Is there a cap per day or something?

**Comment by Kurtchekov** [comment]
I'm not sure there's a cap... could you join our discord server and upload it there?

**Comment by YOYOK9** [comment]
I can try, Whats the discord? And would you like the whole world folder or just those 4 files?

**Comment by YOYOK9** [comment]
Seems like discord has an even smaller MB limit. I was able to upload the 4 .mca files individually though. 
[r.-3.0.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/5152823/r.-3.0.zip)
[r.-3.1.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/5152825/r.-3.1.zip)
[r.-4.0.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/5152826/r.-4.0.zip)
[r.-4.1.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/5152827/r.-4.1.zip)

**Comment by Kurtchekov** [comment]
okay, I'll have a look into those, see if I can find any problems

**Comment by YOYOK9** [comment]
Sounds good, Ill see if I can find a way around for sharing the actual world folder.

**Comment by Kurtchekov** [comment]
I couldn't find the machine in any of those files... =/

**Comment by YOYOK9** [comment]
Hmm, In a few more minutes Ill have a dropbox link with the world file in it. Would you want me to put that here or pvt on discord?

**Comment by Kurtchekov** [comment]
It's up to you, either one works for me

**Comment by YOYOK9** [comment]
Hopefully this will work: https://www.dropbox.com/s/czbkutwqt104vb9/world.zip?dl=0

**Comment by Kurtchekov** [comment]
I've finally finished checking that save and it seems that the server doesn't have any corrupted multiblocks in the overworld. Does it always crash the client nowadays or is the client able to get close to that coke oven, even after the first crashes? Does the client experience lag before the game crashes, for example the chunk takes some time to load and then crashes? Or is the player in the same area for a while a then it suddenly crashes? My current theory is that the server is not sending NBT data quick enough to the client while the client is trying to interact (passively) with the machine, by walking next to it, for example, as it loads.

**Comment by Kurtchekov** [comment]
This is a test build that shouldn't crash that specific machine anymore. Your player should replace their immersive technology jar file with the one inside the provided zip. Once the problem occurs in-game, instead of crashing, it will write to the log the position of the TE in the world, so I can check it over here, in those save files you sent me.
[IT.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/5159005/IT.zip)

**Comment by YOYOK9** [comment]
Answers for the first comment: 
From what he told me the first time it happened he had been in the area of the chunk for a while till it crashed, after that the time between him joining then crashing got shorter on each log in attempt. IE: The server registers he joins, he can see blocks, screen goes white and locks up then crash. As for the rest of the players we just see him join then leave. No noticeable lag from it (we have other lag issues as well) 

Second comment: 
We gave the test build a try, both him and I got the error message in chat. Up side we could move around the unformed multi multiblock with out any issues. (It still crashed even when the multi block wasn't fully formed. Unfortunately when he tried to dismantle it with a tinkers hammer he crashed again. 

WailaError: https://pastebin.com/U6MxDeGB
My latest log: [latest.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/5159963/latest.zip)

His crash: https://pastebin.com/RSWZLmKj

**Comment by Kurtchekov** [comment]
Okay, it's worse than I thought. It's entirely missing the TE data. Run the following commands, it will hopefully remove the corrupted blocks and fix the problem for good.

/fill -1364 13 499 -1364 13 499 immersivetech:stone_decoration
/fill -1363 13 500 -1363 13 500 immersiveengineering:sheetmetal 8

My theory is that the server had problems saving this chunk but not to the point of corrupting the entire world, so you kept on playing, unknowingly, even though these blocks are corrupted beyond recover.

**Comment by YOYOK9** [comment]
Should we be worried about rebuilding the mulitblocks? ie is our current world in a way screwed? The commands did work though. So far no issues in terms of crashing, However there have been some minor issues with some of your other multiblocks, but wasn't sure if I should make a new ticket or if you would like me to just add them to this thread. (non Y-rotating issues)

**Comment by Kurtchekov** [comment]
I don't think the world is screwed but there might be some mod interfering with how the game saves nbt data. Could have been sponge, could be some other mod. It should be fine to build multiblocks, though I suggest not to build that coke oven in the same spot, just to be sure. If you're not sure about the other issues, you can tell me more in the discord channel, it might also speed things up for both of us.

**Comment by YOYOK9** [comment]
Alright sounds good, Ill put then "bugs" there. Thank you so very much for your help.
