### ISSUE TITLE
Out Of Bounds error: -1 Client crash on server

### ISSUE THREAD

**Issue by YOYOK9** [tgstyle/MCT-Immersive-Technology#183]
Not sure of a proper title, any who, One of my server players has found (another) issue it seems. When traveling up via an elevator (openblocks) they get crashed to desktop. On relog same issue. 

ImmersiveTech: 1.12.2-1.8.82
ImmersiveEngineering: 0.12-98
Forge: 14.23.5.2854
MC: 1.12.2
Modpack: BusinessElite-Plus

Crash:  https://pastebin.com/vbq90VDd

-----------------------------------------------
Not sure if it is relevant or not, but after the crashes I noticed our server console spitting out warnings about Mekanism machines within the same area. Can post a screen shot if you feel it is relevant or not.

**Comment by Kurtchekov** [comment]
This should fix it. Let me know if it does, so I can commit the changes.
[IT.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/5296413/IT.zip)
