### ISSUE TITLE
Gas turbine isn't working

### ISSUE THREAD

**Issue by polyzium** [tgstyle/MCT-Immersive-Technology#185]
I set up the gas turbine as intended, diesel on the front, power on the sides, bottom outtake to the tank.
But the thing doesn't want to work, regardless of fuel type, powered by redstone or not, full to the brim or not (I guess this is what you meant by "ingesting enough air"?)
Is there something I'm doing wrong?
Version 1.8.81 @ 1.12.2
<details>
<summary>Screenshot</summary>

![2020-10-03_22 10 23](https://user-images.githubusercontent.com/22579935/94999957-a92e1d80-05c5-11eb-84a8-437d50f42540.png)
</details>

**Comment by Kurtchekov** [comment]
Check starter power consumption and capacity for the gas turbine in the config file, make sure capacity is higher than consumption

**Comment by AWAKEN-1** [comment]
I'm having the same problem, the config file is normal but still doesn't work.

**Comment by tgstyle** [comment]
Make sure you supply it with enough fuel. Make sure to cut the power on the
HV side when you hear it ignite. Also make sure to provide power to the
ignitor.
