### ISSUE TITLE
Right-clicking crash

### ISSUE THREAD

**Issue by Roshag** [tgstyle/MCT-Immersive-Technology#188]
Crash when right-clicking multiblocks (Cooling Tower, Steam Turbine, haven't checked others)
[crash-2020-10-09_19.02.57-client.txt](https://github.com/tgstyle/MCT-Immersive-Technology/files/5356112/crash-2020-10-09_19.02.57-client.txt)

**Comment by Roshag** [comment]
And it looks weird
![image](https://user-images.githubusercontent.com/4922267/95607090-e67e2980-0a63-11eb-8382-c6d2739f8c18.png)

**Comment by Kurtchekov** [comment]
This mod is not compatible with Sponge, that's probably the culprit.

**Comment by tgstyle** [comment]
Optifine also causes the weird look.

**Comment by Roshag** [comment]
Thx, Sponge was the issue, fixed by switching to Magma.
