### ISSUE TITLE
Feature request: Coal boiler (or Gasifier to convert solid fuels to syn-gas to be burnt in the Gas Turbine)

### ISSUE THREAD

**Issue by RRyyas** [tgstyle/MCT-Immersive-Technology#190]
I noticed that nowhere in Immersive mod series is where you can burn coal (or any other burnable items) into usable electrical energy. Currently in order to produce energy from coal and such you would need a different mod (such as Better Boilers mod) to produce steam for the steam turbine. I wish that it doesn't have to require a separate non-Immersive mod to do that, since one of the outputs of the IE excavator is coal ore, and coal being used to produce steam basically started the industrial revolution in Britain. So a boiler like this would have an input from item pipes or conveyor belts that accepts any item that has a Burn Time, and would have an almost identical function as the current diesel boiler. I would suggest that a boiler like this would have a default burntime divider value of about 20, which means that a piece of coal can be burnt in the boiler for about 1600/20 =  80 ticks (or 4 seconds).

Or if you're not able to do that, you could instead make a gasifier that can convert coal, coke or charcoal into syn-gas (synthetic gas), that can then be used in a boiler to produce steam that way.

**Comment by tgstyle** [comment]
We have no plans to implement a solid fuel boiler at this time. We may revisit this in the future in updated versions of Minecraft.
