### ISSUE TITLE
Mod compability for other combustible fuels in the Gas Turbine

### ISSUE THREAD

**Issue by RRyyas** [tgstyle/MCT-Immersive-Technology#191]
I tried to add Natural Gas from the Magneticraft mod into the gas turbine, but it won't accept it, despite it being obvious that it should be accepted and be burnt just like a normal real life gas turbine. So adding compatibility for liquid fuels from other tech mods would be very versatile in a modpack... Also i noticed that the Gas turbine doesn't fully empty the input tank once the fuel is removed, and always stops at like 50 mb of fuel and won't accept another compatible fuel because of that. The only work-around is to break the gas turbine and form it again.

**Comment by tgstyle** [comment]
If you want Natural Gas you will need to use CraftTweaker. We can't account for every mod out there that has a "gas". As for the input tank, the reason for this is the recipe amounts, vs, the tank size. We give it a size and whatever fluid is used may have different usage values.

**Comment by RRyyas** [comment]
What's the zenscript for that?

**Comment by tgstyle** [comment]
It's on the curseforge page.

**Comment by RRyyas** [comment]
Also you forgot about the issue of the gas turbine not emptying the fuel to zero and instead keeps it in the tank

**Comment by tgstyle** [comment]
But I did "As for the input tank, the reason for this is the recipe amounts, vs, the tank size. We give it a size and whatever fluid is used may have different usage values."

**Comment by RRyyas** [comment]
It could easily be done with a few lines of code, so that if the liquid level is lower than the burnrate per tick, then make it zero (or null) without creating fuel byproducts. That way you can switch the fuel around

**Comment by tgstyle** [comment]
Or just build a turbine per fuel. If we had the tank go empty every time
the fluid went below a certain level, it could potentially waste a lot of
fuel. There really is no precedent for doing this, not even IE does it with
the Diesel Generator.
