### ISSUE TITLE
Distilled water fluid id change

### ISSUE THREAD

**Issue by misterplus** [tgstyle/MCT-Immersive-Technology#193]
In immersive tech, the fluid id for distilled water is "dist_water", but now it's "distwater"
Is there some coding reason for this change? Cause this would break existing saves lose all distilled water. It's probably too late to change this back now, but I still wanna know the reasoning behind this. Cause to me, this doesn't seem like a reasonable change.

**Comment by tgstyle** [comment]
It is changed and it won't change back as that would break everyone using immersive technology currently.
