### ISSUE TITLE
Gas Turbine idea and benefits?

### ISSUE THREAD

**Issue by LiskoSlayer63** [tgstyle/MCT-Immersive-Technology#196]
What is the benefits for the gas turbine compared to a steam turbine? Also the Manual entry is very unclear for me. 

Does it needs constantly power to generate power? 
Does the HV input need to be turned off after the turbine is started?
What is the "exhaust gas"?
How do I correctly implement it to produce more energy? (Steam turbine is simple, steam in water out)

Can you explain more clearly how is it supposed to be used? It needs diesel and power yeah, but that's prety much all the information I can get through the manual. Any kind of picture for the layout and the fuel system would be nice too.

Also, what is the purpose of the Cooling Tower?

**Comment by tgstyle** [comment]
I would suggest taking these questions to the official discord channel, many users there are more then willing to answer them.
https://discord.gg/ujY2mV9
