### ISSUE TITLE
Please don't archive older mod versions

### ISSUE THREAD

**Issue by beans-squared** [tgstyle/MCT-Immersive-Technology#197]
I can understand the motivation why, but for me as a modpack developer this can cause me some minor headaches. Because an older, now archived version of Immersive Technology is being used in my modpack, I cannot upload server pack files utilizing this particular version of the mod anymore, because CurseForge won't allow it.

So please, keep your older versions up. I can and will update when I get the chance, but now you've forced my hand.

Anyways Cheers

**Comment by tgstyle** [comment]
Sounds like an issue that should be raised with CurseForge. I will keep older versions up for a bit longer.
