### ISSUE TITLE
Hwyla/Waila crashes when looking at Cooling Tower

### ISSUE THREAD

**Issue by LiskoSlayer63** [tgstyle/MCT-Immersive-Technology#200]
Title says it all. GetItemStack() causes ArrayIndexOutOfBoundsException, very similar to #183.

**Crash log:** https://gist.github.com/LiskoSlayer63/3c24e77ad8958f921d416fd7ad9850b9

**Forge version:** 14.23.5.2847
**Immersive Technology:** 1.8.85

**Comment by tgstyle** [comment]
Try it without optifine.

**Comment by LiskoSlayer63** [comment]
I'll try that tomorrow. Also I need to note that I couldn't reproduce it after that one crash. It happened when I was hugging the tower very closely (I was building a platform around it). After that LoginShield also spawned me *inside* the tower, but I think that's nothing you can do about.

**Comment by tgstyle** [comment]
Closing this issue. If it's still an issue, feel free to re-open.
