### ISSUE TITLE
Multiblock objects behave like grass with shaders enabled

### ISSUE THREAD

**Issue by DejaVuMan** [tgstyle/MCT-Immersive-Technology#204]
Bit of an odd glitch, which I would imagine might have something to do with how the models are rendered. I created a multiblock boiler recently and noticed that the edges of details were waving around in multiple directions as the grass did with the current shaders pack I'm using (Nostalgia v2.3). I've attached to this post a gif file showing just how it looks. This issue seems to be mirrored across all multi-block objects as well but does not affect Immersive Engineering multi-blocks. I've attached to this post screenshots of my graphical configurations and mods that I'm using as well.
[Images of Client Settings and Mods](https://imgur.com/a/gnsd5CC)
[Boiler waving along with grass, while Immersive Engineering's Generator doesn't](https://imgur.com/a/FiKzhRG)

**Comment by tgstyle** [comment]
I would check with the shader pack maker or Optifine, we have no control over what they choose to "wave", it's usually a configuration item. I have used many different shaders with no issue.

**Comment by tgstyle** [comment]
Closing as this is really not our issue to fix.
