### ISSUE TITLE
[1.12.2] NPE Dedicated server crash when placing an Immersive Technology Fluid Trash can next to the Immersive Petroleum gas turbine flue gas exhaust. Recreated in singleplayer.

### ISSUE THREAD

**Issue by ProsperCraft** [tgstyle/MCT-Immersive-Technology#208]
java.lang.NullPointerException
    at mctmods.immersivetechnology.common.blocks.metal.tileentities.TileEntityTrashFluid.fill(TileEntityTrashFluid.java:65)

Dedicated server crash - https://gist.github.com/ProsperCraft/054ef2063afd4cd07ea04072eee2deb3
Reproduced in single player - https://gist.github.com/ProsperCraft/58a04e82dd1a2b409754f899b3480932

MCTImmersiveTechnology-1.12.2-1.8.90

**Comment by Kurtchekov** [comment]
@ProsperCraft Are you trying to anger me? The Gas Turbine is our stuff, not IP! =P
Regardless, I'm fixing it right now, sit tight.

**Comment by Kurtchekov** [comment]
[MCTImmersiveTechnology-1.12.2-1.8.90.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/5648152/MCTImmersiveTechnology-1.12.2-1.8.90.zip)
Give this a try and see if it works, let me know if it does, please.
