### ISSUE TITLE
Advanced Coke Oven Crashing Server

### ISSUE THREAD

**Issue by Keyedrin** [tgstyle/MCT-Immersive-Technology#21]
https://pastebin.com/V1nQESkb

From what I can tell, the Advanced Coke Oven (and possibly other machines we haven't built yet) crash servers when the chunk they are running in is unloaded because of the new sound files. I was not on when the server crashed so I don't know all the details, but if I get more information from my players on it I will post it here.

**Comment by Keyedrin** [comment]
Just an update, after breaking the coke oven, the server seems to be stable again.

**Comment by tgstyle** [comment]
@Kurtchekov maybe some client code still running serverside?

**Comment by Kurtchekov** [comment]
@tgstyle sorry for the delay, I'm still settling in the new apartment and don't have an internet connection for my PC. Will try to fix that problem ASAP.

**Comment by tgstyle** [comment]
@Kurtchekov No worries RL takes priority =)

**Comment by Kurtchekov** [comment]
@tgstyle okay, internet is working now and I have checked the crash. Seems very simple to fix, it's just some code that wasn't supposed to run on the server side. I'll be pushing the fix now.
