### ISSUE TITLE
Suggestion - Nuclear Power Gen

### ISSUE THREAD

**Issue by BlackDragonX007** [tgstyle/MCT-Immersive-Technology#213]
Hello,

I was looking to use your mod in my Mod pack revolving around Immersive Engineering and all the add-on mods.
I love the Steam Turbine / Heat Exchanger / Cooling tower.
What my pack is missing is something to do with all the Uranium that Immersive Engineering will be giving me, I was hoping that you would consider adding a Nuclear Reactor Mutli-block to go with the Steam Turbine / Heat Exchanger / Cooling tower you already have. This could also be a Lead Block (reactor shielding) / Ingot sink as well, Lead Ingots consumed in the Fuel Rod Production (new Metal Press (empty fuel rod) & bottling machine recipes (liquified uranium from a mixer maybe? Distilled water & uranium ingot))

New additions: 
High Temp Coolant (fluid) - Output from Nuclear Reactor (input would be just Coolant).
Run that through the Heat Exchanger - Output Steam
Run that through the Steam Turbine - Output Exhaust Steam
Cooling tower for the Exhaust Steam - Output Distilled water

Additionally there could be a new High Temp Steam (fluid) output from the heat exchanger that when run through the first turbine, gives Steam as its output, allowing a 2nd steam turbine to run using the same amount of fluid but half the power gen, this then outputs the Exhaust Steam which has to go to the cooling tower.

Potential bad stuff:
Too high of a Temperature on the reactor and it scrams, causing all fuel to be destroyed (stack) and "core" needing to be cleaned/replaced (new craftable block?).

If you'd like, I can flesh out the idea more fully or you can run with it how you think fits best.

Thanks,
BlackDragon

**Comment by tgstyle** [comment]
No, this is up to IE to implement.
