### ISSUE TITLE
The gas turbine does not work

### ISSUE THREAD

**Issue by AWAKEN-1** [tgstyle/MCT-Immersive-Technology#215]
The gas turbine didn't work, and I exhausted all my methods.Config files are normal.
![QQ截图20210115170911](https://user-images.githubusercontent.com/77484596/104705106-7400a200-5754-11eb-9b9a-367f651c8aff.png)
Fuel is also provided and electricity is connected on both sides.
Is there any special way to start it?

**Comment by tgstyle** [comment]
Make sure you supply it with enough fuel. Make sure to cut the power on the HV side when you hear it ignite. Also make sure to provide power to the ignitor.
