### ISSUE TITLE
Incorrect documentation regarding gas turbine spark plug

### ISSUE THREAD

**Issue by Hawk777** [tgstyle/MCT-Immersive-Technology#216]
The manual for the gas turbine says this:
> The MV plug uses 1024 IF/t to ignite the fuel if the turbine is not currently burning fuel - this happens on startup and any time the turbine has no fuel for 3 or more ticks.

I see three problems with this sentence.

The first problem is that the consumption should probably be written as 1024 IF, not 1024 IF/t, because it is a one-time consumption when the spark plug fires. Technically it is 1024 IF/t as well, but the duration of one tick is not mentioned, so 1024 IF is more informative.

The second problem is that the ignition grace time is three seconds, not three ticks.

The third problem is that, the way it’s written, to me, it reads as if the spark plug needs to fire if there is no fuel for a *contiguous period* of three seconds. That also seems to make some sense from a realism perspective, since having no fuel for three seconds means the flame goes out and needs to be relit. But how it’s actually implemented in code. Since `ignitionGraceTime` is only reset to 60 in `ignite` and not in `speedUp`, it actually means that absence of fuel for a cumulative total of three seconds since the last time the spark plug fired requires a refire. It seems odd that it would work this way: if I have no fuel for one second and I don’t need to fire the spark plugs, then I wait another minute and have another second with no fuel, and then I wait another minute and have another second with no fuel, why did the flame go out the third time but not the first or second? To me it would make sense that `speedUp` should reset `ignitionGraceTime` to 60, because burning more fuel should “refresh” the flame. However, even if the current behaviour is intended, then I think the documentation doesn’t reflect that accurately.

This is with 1.8.91.

**Comment by tgstyle** [comment]
If you feel inclined to do so, you can submit a PR for this with the changes on this file.

https://github.com/tgstyle/MCT-Immersive-Technology/blob/Latest/src/main/resources/assets/immersivetech/lang/en_US.lang

**Comment by Hawk777** [comment]
Happy to do that if you can confirm that the behaviour mentioned in (3) is intended behaviour and not a bug. Is it intentional that the grace time is three seconds cumulative, not three contiguous seconds? If it’s a bug I’d rather not document it in the manual but instead in a ticket.

**Comment by voidsong-dragonfly** [comment]
That's unintentional. It is supposed to be contiguous, it probably got a little wonkily implemented.
