### ISSUE TITLE
[Feature request] Redstone Probe Connector functionality

### ISSUE THREAD

**Issue by cloakable** [tgstyle/MCT-Immersive-Technology#217]
Currently, putting a redstone probe connector on a gas turbine outputs no redstone signal; it would be useful from a monitoring perspective to have it output a 0-15 signal proportional to the turbine RPM. With a little bit of redstone work, this would allow for a player to safely start the turbine remotely, without getting close to the hv wires likely connected.

**Comment by tgstyle** [comment]
No further changes will be made to the mod.
