### ISSUE TITLE
Graphical issue with multiblocks

### ISSUE THREAD

**Issue by QuantumBlink1337** [tgstyle/MCT-Immersive-Technology#218]
Hello,
I'm currently experiencing a graphical error viewing some multiblocks, including the Heat Exchanger and the Distiller. 
![image](https://user-images.githubusercontent.com/37894528/105750146-f6822200-5f09-11eb-9b10-4087780f8bef.png)

[Here is my full log:](https://gist.github.com/QuantumBlink1337/514577885213f3cc64cac233231f72c8). 
Using Immersive Technology 1.8.93 and Immersive Engineering 0.12-98.

**Comment by tgstyle** [comment]
Can you post a list of all the mods you are using? Does it render properly on a world reload?

**Comment by QuantumBlink1337** [comment]
[Here's my modlist](https://gist.github.com/QuantumBlink1337/1c53ebb262acab8c8a48a15be918523d)

I revisited the base where this is occuring (this is on a server) and broke the multiblock and reformed it. It was fine for a few seconds, then I tabbed out and it continued with the glitch.  The world has been restarted numerous times since this original post.

**Comment by tgstyle** [comment]
Remove spongeforge from the server.

**Comment by QuantumBlink1337** [comment]
We aren't using SpongeForge? FTB Utilities is our command mod.

**Comment by QuantumBlink1337** [comment]
Hold up, sorry. That mod list is really outdated no idea why.

**Comment by QuantumBlink1337** [comment]
Sorry about that. I updated my previous comment.

**Comment by tgstyle** [comment]
Any way to get a mod list from the server?

**Comment by QuantumBlink1337** [comment]
https://gist.github.com/QuantumBlink1337/55b3f583c109757c98177bf0998bb246 mod list dumped from server

**Comment by tgstyle** [comment]
Does it do it if you load the server save game on a client?

**Comment by tgstyle** [comment]
Closing, if there are further issues this can be re-opened.
