### ISSUE TITLE
Way to remove (or burn) residual fluid in the gas turbine fuel tank

### ISSUE THREAD

**Issue by Hawk777** [tgstyle/MCT-Immersive-Technology#222]
The gas turbine’s fuel tank has a 10,000 mB capacity. Many mods move fluids around in whole-bucket units. None of the recipes consume factors of either of these numbers: biodiesel burns 160 at a time leaving zero residue after 4 buckets, gasoline burns 800 at a time leaving zero residue after 4 buckets, and diesel burns 114 at a time leaving zero residue after a whopping 57 buckets.

It’s nice to be able to switch fuels sometimes. Maybe you have both a plant and a petroleum setup so you want to switch between diesel and biodiesel. Maybe you have a petroleum setup and not much use for gasoline, so you want to mainly burn diesel but once in a while do a gasoline burn just to free some space in your storage tanks. There are plenty of reasons why this can be useful.

Unfortunately, the turbine refuses to burn the residue, refuses to let it be pumped out of its internal storage tank, and also refuses to allow anything else to be pumped in while there is residue present. That means you have to do some pretty awkward manipulations to reach LCM(1000, x) units of fuel inserted so that you have a residue of zero and can switch fuels.

Maybe that’s intentional, and it’s a hint that I should be building a more complicated fluid management network; feel free to close as WONTFIX if that’s the case. If it’s not intentional, maybe something could be done about it? I’m not sure how this could be made to work; my initial thought was to use a Buildcraft wooden pipe with pulsar to try and pump the residue out, but that didn’t work, presumably because of `canDrainTankFrom` returning `false` for the input tank. Presumably allowing it to be drained via the usual connection would be problematic during normal operation.

**Comment by tgstyle** [comment]
Yeah this is going to be a WONTFIX. CraftTweaker can be used to adjust the fuel ratios. It can even be solved by using a turbine for Diesel and one for Gas.
