### ISSUE TITLE
[Feature Request] Heat Exchanger GUI

### ISSUE THREAD

**Issue by JamesHezzy** [tgstyle/MCT-Immersive-Technology#223]
Not an Issue, just a suggestion for the heat exchanger. It'd be nice to have a GUI similar to that of the steam boiler and solar boiler to enable easy checking of if the machine is receiving water and power and in turn producing steam for the turbine.

**Comment by tombull89** [comment]
Agreed. Whilst you can use tooltip mods like The One Probe to see what is in a IT machine, a GUI would be helpful.

**Comment by Gliese-832-c** [comment]
Especially since TOP isn't accurate to the single digit, while a GUI shows exactly the amount (at least it does in the boiler).

**Comment by tgstyle** [comment]
No further changes will be made to the mod.
