### ISSUE TITLE
Localized text formatting issues

### ISSUE THREAD

**Issue by Aemande123** [tgstyle/MCT-Immersive-Technology#23]
Hello,I am a Chinese minecraft player and I am translating this mod into Simplified Chinese
I found that the key entry of the localized text of this module is duplicated

![17](https://user-images.githubusercontent.com/23289812/73608254-d2904700-45fb-11ea-9f7e-cd7746e0b13b.jpg)

In addition, After correction,the maximum power generation of alternator entries in the manual cannot be displayed

![18](https://user-images.githubusercontent.com/23289812/73608258-d91ebe80-45fb-11ea-931b-649873591c82.jpg)

This mods is great, I will submit the latest Simplified Chinese translation after the problem is fixed

**Comment by tgstyle** [comment]
Working on the fix now, the English version will be corrected and uploaded shortly. You can use this for the base to translate from.

**Comment by tgstyle** [comment]
You should be able to translate from this file

https://github.com/tgstyle/Immersive-Technology/blob/Latest/src/main/resources/assets/immersivetech/lang/en_US.lang

**Comment by Aemande123** [comment]
> You should be able to translate from this file
> 
> https://github.com/tgstyle/Immersive-Technology/blob/Latest/src/main/resources/assets/immersivetech/lang/en_US.lang

thank you very much!
