### ISSUE TITLE
[Feature Request] Update to newer versions of forge?

### ISSUE THREAD

**Issue by ajsnarr98** [tgstyle/MCT-Immersive-Technology#230]
Hi, I was a huge fan of the immersive tech mod, and its awesome that you are continuing with this mod. I haven't been able to find previous posts about this, so wanted to ask directly.

What made you continue developing this mod for 1.12.2, even now when that version of forge is deprecated? Do you have plans to update the mod to the newer forge APIs?

**Comment by Gliese-832-c** [comment]
Because you don't always have to jump to the absolutely latest version of Minecraft. 1.12.2 has much better performance (especially TPS-wise, which is the more important one), has the most and best mods, and modpacks.
