### ISSUE TITLE
SUGGESTION: Coal fired boilers.

### ISSUE THREAD

**Issue by NightScale5755** [tgstyle/MCT-Immersive-Technology#231]
Just as it says on the tin. A less efficient boiler that burns coal, charcoal, and coal coke.
Reasons for this: 
* An early game boiler, when you don't have stockpiles of biodiesel.
* You have a coal fired power plant on your world, and want it to be functional.
* You're living in the 1910s in your Minecraft world.
* You have that one pollution mod, and want to make your world uninhabitable.

Thanks for reading my suggestion.

**Comment by Gliese-832-c** [comment]
I agree. Coal power is completely missing from the world of IE and addons. It especially makes sense given the aesthetic/tech level/time period of IE.

I would propose to make it different though. Just add an item slot, which can burn any item that can be burned in a furnace. No need to limit it to just those items.

The config file could have a multiplier. (So if coal burns for 1600 ticks, and the multiplier is at 0.25, then it would burn for 400 in the boiler. Etc.)

**Comment by BrownHarf** [comment]
I agree

**Comment by juraj-hrivnak** [comment]
I agree too.

**Comment by alanecredic** [comment]
i agree

i need that                                  just imagine

**Comment by ThePiGuy24** [comment]
agreed, been wanting to make a massive coal/wood plant for a while now

**Comment by tgstyle** [comment]
No further changes will be made to the mod.
