### ISSUE TITLE
Solar Tower Not Outputting Steam

### ISSUE THREAD

**Issue by GuineaPig2000** [tgstyle/MCT-Immersive-Technology#236]
Solar tower converts distilled water to steam, but stores the steam despite pipes hooked up to output. It does not flow to the steam turbine. when I installed a metal bucket, and manually emptied the solar tower, it powered the steam turbine

**Comment by voidsong-dragonfly** [comment]
Version?

**Comment by GuineaPig2000** [comment]
MCTImmersiveTechnology-1.12.2-1.9.96.jar

**Comment by voidsong-dragonfly** [comment]
Picture of the setup?

**Comment by GuineaPig2000** [comment]
![2021-08-26_21 01 52](https://user-images.githubusercontent.com/70278342/131055144-d09fae5e-cc89-4bd0-a554-5cfbb676ee1b.png)
![2021-08-26_21 01 57](https://user-images.githubusercontent.com/70278342/131055146-4662dae6-66c0-4489-ad6e-d3f08d0e3d4d.png)
![2021-08-26_21 02 03](https://user-images.githubusercontent.com/70278342/131055147-7e74a502-53a0-4760-8d9e-ee5642ed1bc6.png)
![2021-08-26_11 28 03](https://user-images.githubusercontent.com/70278342/131055148-1679f787-115e-4b06-bdad-759de8d5eba5.png)

**Comment by voidsong-dragonfly** [comment]
You have like 4 reflectors. What the hell are you doing. Your recipe time will run.... uhhh...  1/57th of a turbine.

**Comment by GuineaPig2000** [comment]
How do you get 228 reflectors all within a 5 block space?

**Comment by GuineaPig2000** [comment]
Also even when the steam is full in the tower it is still not outputting

**Comment by voidsong-dragonfly** [comment]
You need to regenerate your configs. The default range is 14-48 now.

**Comment by GuineaPig2000** [comment]
Ok thanks, but what about the output

**Comment by voidsong-dragonfly** [comment]
It's likely outputting! It just takes _57 times as long_ to output.

**Comment by GuineaPig2000** [comment]
![2021-08-26_21 07 02](https://user-images.githubusercontent.com/70278342/131055484-1c2aa73f-99f3-4c8e-ae58-e926b5472b9e.png)

**Comment by GuineaPig2000** [comment]
So is output dependent on conversion rate despite already being stored?

**Comment by voidsong-dragonfly** [comment]
Possibly? I don't remember. Either way, I would in that case check pipe connections, as I have tested autooutput for the machine before.
