### ISSUE TITLE
How do i get my solar reflectors to face the solar tower?

### ISSUE THREAD

**Issue by GuineaPig2000** [tgstyle/MCT-Immersive-Technology#237]
![2021-08-27_14 22 54](https://user-images.githubusercontent.com/70278342/131172697-2b9a607c-1ff2-4325-af94-38605931d47f.png)
![2021-08-27_14 22 58](https://user-images.githubusercontent.com/70278342/131172702-584f65b4-8da8-4e73-86da-4f043e5ad4ac.png)
![2021-08-27_14 22 53](https://user-images.githubusercontent.com/70278342/131172706-c86c69af-33f5-4895-976e-881270fb6f23.png)

**Comment by voidsong-dragonfly** [comment]
They're on the wrong level. Move the tower down one, the foundation is meant to be sunk into the ground

**Comment by voidsong-dragonfly** [comment]
Also, move to the discord.
