### ISSUE TITLE
1.12.2 deprecated for Immersive Engineering

### ISSUE THREAD

**Issue by trexxet** [tgstyle/MCT-Immersive-Technology#238]
IE dev has [stated](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering?comment=4770) that 1.12.2 version won't be updated, so it would be nice to see this mod for 1.16.5 :)

**Comment by voidsong-dragonfly** [comment]
Yes, and have you not yet realized that **asking indie or nonprofessional devs for updates/etas/etc** is seen as **incredibly rude**? It'll happen when it happens, *we are not at your beck and call, and do not have infinite time*. Don't do this again.
