### ISSUE TITLE
[Crash] Cannot create null fluid (WIthout CraftTweaker or custom fluids)

### ISSUE THREAD

**Issue by Desempregago** [tgstyle/MCT-Immersive-Technology#240]
Forge 2855
Immersive Engineering 0.12-98
Immersive Technology 1.9.96
Mod list included in the crash report

[Crash Report](https://pastebin.com/NbSiLA0D)
![image](https://user-images.githubusercontent.com/14002834/135344453-8cff78d8-18ce-46c6-9e65-fdf5e98a12db.png)

**Comment by Desempregago** [comment]
PS: Crash at Startup

**Comment by Dreeam-qwq** [comment]
fix in https://github.com/tgstyle/MCT-Immersive-Technology/commit/83b90e5a99905427189aa90eebb416ef5a9a3f36
