### ISSUE TITLE
[1.12.2] [suggestion] rotate Redstone Timer with the Engineer's Hammer

### ISSUE THREAD

**Issue by Sheenus** [tgstyle/MCT-Immersive-Technology#241]
Presently the Redstone Timer cannot be rotated at all; this leaves the redstone control for the Timer to perpetually face South. Needless to say, this can interfere significantly in smaller builds, where the freedom to place the timer might be limited, without interfering in other redstone-sensitive devices.

Currently, right-clicking with the Engineer's Hammer does not rotate the device, it only changes the output channel for the redstone wire connection. I only suggest the Hammer because it'd be the most mechanically appropriate for 1.12, but I guess you could make it any of the IE tools to potentially implement this functionality.

Tested current functionality on this setup:
- Minecraft 1.12.2
- Forge 14.23.5.2855
- ImmersiveEngineering-0.12-98
- MCTImmersiveTechnology-1.12.2-1.8.94
- jei_1.12.2-4.16.1.301
- Hwyla-1.8.26-B41_1.12.2

**Comment by tgstyle** [comment]
No further changes will be made to the mod.
