### ISSUE TITLE
Unable to remove default MeltingCrucible recipe

### ISSUE THREAD

**Issue by MasterEnderman** [tgstyle/MCT-Immersive-Technology#248]
Hello,

I'm trying to remove the default cobblestone to lava recipe in the Melting Crucible / Solar Melting Crucible.

For that I used `MeltingCrucible.removeRecipe(<minecraft:cobblestone>);` (after importing it) in my crafttweaker script, but after restarting the recipe still shows up in JEI and cobblestone can still be processed in the Crucible. There aren't any errors in the ingame chat nor in the `crafttweaker.log`.

Forge: 14.23.5.2854
CraftTweaker: 4.1.20.669
ImmersiveEngineering: 0.12-98
ImmersiveTechnology: 1.9.98

**Comment by AngelTechnic** [comment]
what about removing lava instead of cobblestone?

**Comment by MasterEnderman** [comment]
https://github.com/tgstyle/MCT-Immersive-Technology/blob/Latest/src/main/java/mctmods/immersivetechnology/common/util/compat/crafttweaker/MeltingCrucible.java

The method requires the item input as IItemStack.

**Comment by MasterEnderman** [comment]
Can be fixed by disabling the default recipe registration in the config file.
