### ISSUE TITLE
Combining fluids from mod IC2

### ISSUE THREAD

**Issue by NorthHusky** [tgstyle/MCT-Immersive-Technology#261]
MC version: 1.12.2
IC2: industrialcraft-2-2.8.221-ex112
IE: ImmersiveEngineering-0.12-98
IT: MCTImmersiveTechnology-1.12.2-1.9.100
CT: CraftTweaker2-1.12-4.1.20.674

Tell me please, I want to make one liquid like "**distilled water**", such a liquid is in your mod and in the **IC2** mod, I want to make something like a tag through **CraftTweaker** and use it in machine recipes in different mods. Is it possible to do this, please tell me the script ZS for **CraftTweaker**? Specifically in your mod, I wanted to use this tag for the Solar Tower mechanism.

**Comment by voidsong-dragonfly** [comment]
Wrong repo. Ask the CT people
