### ISSUE TITLE
Unable to make etching acid from Immersive Inteligence with this mod installed 

### ISSUE THREAD

**Issue by Smokedeuch** [tgstyle/MCT-Immersive-Technology#262]
Caused by the distiller making Immersive Technology chlorine that can then NOT be pumped into the mixer and combined with iron grit to make etching acid

**Comment by tgstyle** [comment]
There will be no more updates for this mod. This doesn't seem like an issue with the mod, more that a recipe needs to be added. You can use CraftTweaker to fix this.
