### ISSUE TITLE
Cooling tower not working

### ISSUE THREAD

**Issue by Texassplitter0** [tgstyle/MCT-Immersive-Technology#263]
The cooling tower is not working, have already tried every combination of liquids that should work (steam, exhaust steam and high pressure steam on the red marked side; water and distilled water on the blue marked side) However, it still works not yet. Can anyone help?

**Comment by tgstyle** [comment]
For help seek out the discord channel. Also JEI is a good resource.
https://discord.gg/ujY2mV9
