### ISSUE TITLE
Fluid compatibility with Nuclearcraft

### ISSUE THREAD

**Issue by michelegargiulo** [tgstyle/MCT-Immersive-Technology#264]
Would it be possible to rename the registry name of some fluids to match others of other mods? This reduces the number of duplicate fluids that serve the same purpose.

My specific request would be to unify the following fluids:

"moltensodium" -> "sodium" (Nuclearcraft and others)
"exhauststeam" -> "exhaust_steam" (Nuclearcraft)
"highpressuresteam" -> "high_pressure_steam" (Nuclearcraft)

It would be nice to have at least a config option, so to both maintain backwards compatibility with existing world and also more versatility for pack makers.

**Comment by tgstyle** [comment]
No further changes will be made to the mod. You can use Crafttweaker to achieve this.
