### ISSUE TITLE
Mod description addition

### ISSUE THREAD

**Issue by Primitive-Human** [tgstyle/MCT-Immersive-Technology#265]
Too many idiots on a certain subreddit ask why their advanced coke oven doesn't work. I've to tell each one of them that it's been removed since version 1.9.95 and that they need to downgrade to version 1.9.94 if they really want it.

It might be better if you specified on the CurseForge description page that, in case they want the removed advanced coke oven, that they should download version 1.9.94 specifically.

**Comment by tgstyle** [comment]
It already says it in every changelog for all 1.9 releases.
