### ISSUE TITLE
Re-adding the Advanced Coke Oven?

### ISSUE THREAD

**Issue by bigyihsuan** [tgstyle/MCT-Immersive-Technology#266]
I did some investigating why the Advanced Coke Oven existed in old versions and not in the current one, and it seems the Advanced Coke Oven was buggy.

Why was this the case? Was there something inherently wrong with the Advanced Coke Oven that caused these bugs? Would it be possible to re-add the Advanced Coke Oven?

**Comment by tgstyle** [comment]
no

**Comment by bigyihsuan** [comment]
> no

That's not helpful. What were the issues that led to the coke oven's removal?
