### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dan4oby** [tgstyle/MCT-Immersive-Technology#268]
Crash when moving redstone timer with pistone

**Comment by tgstyle** [comment]
I would just use a timer from a different mod. This issue will not be fixed, this mod is unsupported.

**Comment by Ashen-sysadmin** [comment]
Since you are still accepting pull requests from people, you shouldn't be closing issues as unsupported. 

You might not personally be working on the project, but closing issues like this makes the github page useless for other people.

**Comment by tgstyle** [comment]
Spare me the dramatics. If you have a PR to fix the issue then do it. I am not at your beck and call to fix issues, nor am I actively doing so. The PR was submitted and accepted by someone who actively decided to participate versus complain about it.

**Comment by tgstyle** [comment]
Not only that, there was no crash log or detail on how to reproduce this error.
