### ISSUE TITLE
Cannot form alternator multiblock

### ISSUE THREAD

**Issue by Aballesta28** [tgstyle/MCT-Immersive-Technology#269]
When I try to form the alternator for the steam turbine, I cannot access the block that I'm supposed to hit with the hammer because the block from what I assume to be the axle of the steam turbine blocks it. 

What I do is break that block, activate the alternator first and then the turbine, I assume that both structures must be connected or "activated" (meaning hit with the hammer) in a certain order, because so far I haven't been able to get the setup running.

Thank you in advance!

**Comment by Primitive-Human** [comment]
If you're playing with v100 or whichever latest version of MCT there is, you shouldn't need to be doing this; hammering the middle block on both ends of the turbine-alternator multiblock separately forms them.

Check your alternator placement; the light engineering blocks should be facing away from the turbine.
