### ISSUE TITLE
Sound Exception on Server

### ISSUE THREAD

**Issue by tgstyle** [tgstyle/MCT-Immersive-Technology#28]
@Kurtchekov this exception is popping up on server logs.

https://gist.github.com/tgstyle/0efb94301437be2939dc2ddfab7c41f4

**Comment by Kurtchekov** [comment]
The more I deal with Forge, the more I hate it. Basically, that's a message supposed to be ONLY sent from the server to the client, but it seems we're forced to register a handler on the server side of things. I've created an empty class for handling the message on the server, should work just fine now.
