### ISSUE TITLE
The solar tower does not work with mirrors

### ISSUE THREAD

**Issue by Banana-fan** [tgstyle/MCT-Immersive-Technology#280]
When I put the mirrors in front of this solar tower, they do not change their texture, and the tower does not see them, but during the day it shows as if all 4 mirrors are installed, although they are not even there and how can I not follow the mirrors

**Comment by Banana-fan** [comment]
![17323626941043041588158324531519](https://github.com/user-attachments/assets/7a41182e-5882-40cc-97fb-f2164d150860)
![17323627453821870924233207688153](https://github.com/user-attachments/assets/18a9dc1d-c7c2-4029-86a9-2fd57c6204d1)

**Comment by tgstyle** [comment]
Place them above the base cement block on the tower.
