### ISSUE TITLE
Advanced Coke Oven Graphical Issue!

### ISSUE THREAD

**Issue by JotunnF2002** [tgstyle/MCT-Immersive-Technology#44]
For some reason this just started happening although I didn't see this happening 5 days ago on the same version of Immersive Tech. So what happens is you build the advanced coke oven and when you open the GUI it starts creating more around that are just there with no hitbox. I have noticed that sometimes when this happens it doesn't function at all but its 50/50. It sometimes makes sound when it's on. The preheater also seems to be doing this. The oven also is no creating creosote oil but it looks like it does sometimes, idek at this point it keeps changing shit up on me. I'll add some screenshots. Thanks!

Version: ImmersiveTechnology-1.12.2-1.6.43

![2020-02-20_11 07 06](https://user-images.githubusercontent.com/61285992/74954777-a2a1bb80-53d1-11ea-9b2f-2c45f718f6c6.png)
![2020-02-20_11 07 11](https://user-images.githubusercontent.com/61285992/74954780-a33a5200-53d1-11ea-9805-c304d89a0bf0.png)
![2020-02-20_11 20 16](https://user-images.githubusercontent.com/61285992/74955762-214b2880-53d3-11ea-8d28-4e5391b3072a.png)

**Comment by tgstyle** [comment]
Interesting, have you tried breaking the multiblock and reforming it?

**Comment by Kurtchekov** [comment]
Can you send us over your save file? I need to take a look into it

**Comment by JotunnF2002** [comment]
I have tried reforming it many times

**Comment by JotunnF2002** [comment]
[New World.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/4233376/New.World.zip)

After this happened to me on my own server I tried it in this creative world in singleplayer and I saw the same issue so here is the single player world.

**Comment by Kurtchekov** [comment]
@JotunnF2002 I see a coke oven here and it's rendered correctly. Where's the one in the screenshots?

**Comment by Kurtchekov** [comment]
Btw, I have noticed you're using Sponge. That might be causing an issue.

**Comment by JotunnF2002** [comment]
Ok, I will remove spongeforge and try it. The one in the screenshots is on my server and it does the same thing on singleplayer so thats why I just sent the singleplayer one.

**Comment by JotunnF2002** [comment]
You know what, never mind any of this it was spongforge causing this, thank you for the help anyways. I'm just gonna use ftbutil from now on. Thanks.
