### ISSUE TITLE
Left a machine name with the old format

### ISSUE THREAD

**Issue by Federsavo** [tgstyle/MCT-Immersive-Technology#46]
In your last update you fixed the machine names but you missed the advanced coke oven:

*IT : CokeOvenAdvanced* should be *IT:CokeOvenAdvanced*

**Comment by tgstyle** [comment]
For compatibility with Immersive Tech it has to stay internally as CokeOvenAdvanced. Renaming it would most likely cause issues.

**Comment by tgstyle** [comment]
Sorry I was thinking the internal name, I see it now. I will remove the spaces.

**Comment by tgstyle** [comment]
Fixed #https://github.com/tgstyle/MCT-Immersive-Technology/commit/c6b6e65cb1864a8d309e75760176fb96a6638403
