### ISSUE TITLE
[suggestion / feature request] make boiler accept lava

### ISSUE THREAD

**Issue by ghost** [tgstyle/MCT-Immersive-Technology#53]
https://www.reddit.com/r/feedthebeast/comments/f8o9vb/immersiveengineering_use_for_lava/
I put to gether a small IE based pack together - had original IT in it - just discovered your mod a few minutes ago
I have lots and lots of lava in the overworld and search for an use for it - as suggested by some user on reddit it would be cool if the boiler would accept lava - or at least if there would be an option to enable it to accept lava would be nice to see (if on by default - has to be debated about - but at least config would be neat to see soon)

**Comment by tgstyle** [comment]
This can already be done with CraftTweaker scripts. Examples are on the CurseForge page.

**Comment by ghost** [comment]
and what do you suggest for those not to use recipe tweaker mods?

**Comment by tgstyle** [comment]
That is exactly CraftTweaker it is designed for, to modify settings outside the scope of settings not provided by the mod author. I do not plan on adding lava, there is already a solution for it.

**Comment by ghost** [comment]
k - I setup crafttweaker now - just for the damn sake of it - and it works (although I don't understand what's the " * 5" for the lava means - nvm
now I would appreciate if you may can tell me what line I have to add so it does show up in JEI - thx in advance

**Comment by tgstyle** [comment]
It should just show up by pressing U on lava.

**Comment by Kurtchekov** [comment]
@cryptearth The Boiler has 2 different categories in JEI, one for fuels it acccepts and another for what it actually outputs. If you press U on the lava fluid in JEI (not the bucket), it should show there. About the CT script, the * 5 is there because <liquid:lava> (or any fluid, really) is just 1 mb, the * 5 is so that you can get 5mb instead.

**Comment by ghost** [comment]
well, I just added CT - put a simple one liner into the scripts folder with the line from curseforge - it does work, but it does not show up in jei - neither if i press u on lava nor r on the boiler - hence I'm asking what I need to add to also make it show up in JEI

**Comment by ghost** [comment]
well - I guess the issue is crafttweaker - I only set up the script only server side - but not client side
so when the client connects to the server it works on the server - but there seems no sync from the server to the client if they don't have matching scripts ... guess that can't be fixed by mod but would need re-work of CT ... k, sorry for having bothered you

**Comment by Kurtchekov** [comment]
I have added lava to the boiler on my end using CT, just to make sure there's no bug.
![javaw_2020-02-26_04-13-01](https://user-images.githubusercontent.com/10952836/75305391-9e045980-584e-11ea-9f60-f0ebe920c529.png)

But yeah, the crafttweaker script has to be both on the server and client.

**Comment by tgstyle** [comment]
As @Kurtchekov mentioned, to see things on the client, they need to be on the client. The script and crafttweaker both need to run on the client as well.

**Comment by ghost** [comment]
yea - just figured that out ... guess that's an issue CT didn't had in mind as it claims itself designed for modpacks - and usual on packs the configs are also packed into the client so it matches the server ... nvm - thx for your effort anyway - guess I have to decide if I either just get along with it not show up in JEI or have to force anyone want to play along with me to add this small one-liner to the client
exactly THAT is the reason why I asked to had it added by the mod intself - as CT isn't that great of a solution - at least in the 1.12.2 version (btw: does anyone know if there're any newer versions of IE available?)

**Comment by tgstyle** [comment]
CT is a perfect solution and does exactly what it is designed for, it's possibilities are endless, and I am surprised by that comment. There is a reason why it has 50+ million downloads.
I would suggest you explore the possibilities. 
https://docs.blamejared.com/1.12/

FYI, coming on here and giving grief over not getting your way is not a good way to win us over. We are unpaid for this work, and provide the benefits of our talents free of charge. Then you have the gall to complain about our providing help and even expect more.

Ask IE when and if they are going to release a new version.
