### ISSUE TITLE
Typo in the energy trash can tooltip

### ISSUE THREAD

**Issue by Federsavo** [tgstyle/MCT-Immersive-Technology#57]
There should be a spacing between 'if' and '0'

![2020-02-26_22 38 16](https://user-images.githubusercontent.com/29519894/75392001-7911f400-58eb-11ea-9752-50ecc53873ca.png)

**Comment by tgstyle** [comment]
Very odd, I will have to look at that. Are you using a localization that is not en_US?

**Comment by Kurtchekov** [comment]
@tgstyle I'm on it.

**Comment by Federsavo** [comment]
No, I'm using en_US

**Comment by tgstyle** [comment]
Fixed in the next release, trash cans received a complete overhaul.
