### ISSUE TITLE
Right-click trash can crash

### ISSUE THREAD

**Issue by EnterFor** [tgstyle/MCT-Immersive-Technology#64]
The report：https://paste.ubuntu.com/p/n6YWrrSXPJ/
The picture：https://i.loli.net/2020/02/29/kcly4avg1opb8On.png

I'm not good at English. I'm Chinese
I'm scared, I'm scared to click on it!

**Comment by tgstyle** [comment]
Try updating to the latest version of the mod. This issue should already be fixed.
