### ISSUE TITLE
Bug using IT and TOP and TOP addons (the one probe) [1.12.2]

### ISSUE THREAD

**Issue by Federsavo** [tgstyle/MCT-Immersive-Technology#72]
If both The One Probe and The One Probe Addons are installled it happens a strange bug in the tooltip where the energy is full but you can see only in his central part. This doesn't happen if only TOP  is installed.

![2020-03-12_16 08 44](https://user-images.githubusercontent.com/29519894/76575005-486eb480-64be-11ea-92d9-dc379a0834e5.png)

![2020-03-12_16 08 52](https://user-images.githubusercontent.com/29519894/76575011-4b69a500-64be-11ea-8f93-a24adab3d752.png)

**Comment by tgstyle** [comment]
I'll have to see if there is anything that can be done. The TileEntity is the middle block. That is why it works hovering over it and not the others.

**Comment by tgstyle** [comment]
Thanks @Kurtchekov , this issue uncovered a larger issue that was held over from Immersive Tech code. It is fixed in the next upcoming release.
