### ISSUE TITLE
Feature request: Disabling multiblocks in config deletes Engineer's Manual entries

### ISSUE THREAD

**Issue by ghost** [tgstyle/MCT-Immersive-Technology#74]
I've disabled both the Advanced Coke Oven and Solar Tower multiblocks in the Immersive Technology config, but their entries remain in the Engineer's Manual. This is understandably confusing to players using my modpack. Could you please make it so disabling the multiblocks also removes their pages in the manual?

**Comment by tgstyle** [comment]
Was added in this commit
https://github.com/tgstyle/MCT-Immersive-Technology/commit/14f344c587e0ea1e2419144016e90e5f8b9f9cc2
