### ISSUE TITLE
Startup crash v1.7.51

### ISSUE THREAD

**Issue by siteonfly** [tgstyle/MCT-Immersive-Technology#84]
Last patch didn't fixed crash.
Here is [log](https://paste.dimdev.org/tijugenagi.mccrash)

**Comment by Kurtchekov** [comment]
Can you add CoFH Core to your game and see if that fixes the problem? https://www.curseforge.com/minecraft/mc-mods/cofh-core

**Comment by tgstyle** [comment]
Is it actually needing RF API?
https://www.curseforge.com/minecraft/mc-mods/redstone-flux/

**Comment by siteonfly** [comment]
> 
> 
> Can you add CoFH Core to your game and see if that fixes the problem? https://www.curseforge.com/minecraft/mc-mods/cofh-core

Thank you. Adding CoFH Core and Redstone flux resolved problem.

**Comment by jarezzz** [comment]
At least add the dependency on curseforge page

**Comment by tgstyle** [comment]
It will be a required dependency in the mod in the next version. A commit has already been added for it.
