### ISSUE TITLE
Request: Icons (Items) in JEI to represent the multiblocks.

### ISSUE THREAD

**Issue by CelestialPhoenix** [tgstyle/MCT-Immersive-Technology#90]
It'll be very useful to add a set of items to the game, representing the multiblocks. (using the same icon that appears in JEI when viewing processing recipes)

This way I can search for 'Distillation Tower' in JEI, and see the Distillation Tower icon/item in the search result.
In addition if I could directly view the processing recipes from here, instead of searching for a known output and tracking back to see the processing recipes.

Also for pack devs, this item/icon would be useful for putting in questbooks, giving as a trophy, or attaching extra information to with JEI descriptions.

**Comment by Kurtchekov** [comment]
I've tried to do that a few months ago but didn't really manage to figure out how to. I guess I could take another look into this and see what can be done.
