### ISSUE TITLE
[1.12.2] Bug filling a bottle with creosote using advanced coke oven

### ISSUE THREAD

**Issue by Federsavo** [tgstyle/MCT-Immersive-Technology#91]
I've tested with only IE, IT and Railcraft
Railcraft adds creosote bottles.
 If you use the advanced coke oven to fill a bottle of creosote, it works perfectly but the meter of creosote oil doesn't go down. This is only a visual glitch because if you smelt another coal into the advanced coke oven the meter shows the right amount of creosote oil.

**Comment by Kurtchekov** [comment]
I will look into it.
