### ISSUE TITLE
Server crash related to steel tank

### ISSUE THREAD

**Issue by ghost** [tgstyle/MCT-Immersive-Technology#97]
Crash report: https://pastebin.com/MAiMSAcA

**Comment by Kurtchekov** [comment]
[immersivetech.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/4417342/immersivetech.zip)

Can you replace the mod with this jar? It might fix the problem.

**Comment by ghost** [comment]
Sure, I'll try it and report back when the player with the tank logs in.

**Comment by ghost** [comment]
Everything seems fine now, thank you very much for the quick reply yesterday.
